#!/bin/bash

sleep 2

# Type of news set (relevant or irrelevant)
type="relevant"

# Input dataset path
path_input_dataset="../../phase 8/data/text_success_with_summary_sample_filtered.csv"

# Output dataset path, with summary generated by llm
path_output_dataset="text_success_with_summary_sample_filtered_with_summary_generated.csv"

nohup python3 summary_generator.py  $type "$path_input_dataset" $path_output_dataset > summary_generator.log 2>&1 &